[pytest]
;addopts = -v
asyncio_mode = auto
markers =
    unit: unit tests (fast, no I/O, no external dependencies)
    integration: integration tests
    system: end-to-end tests
    uc: use cases tests
