from dataclasses import dataclass, field
from datetime import datetime
from typing import List, Optional

from a_core import DTO
from b_domain.value_objects.enums import EnergyLevel, Priority
from c_application.dtos.recurrence_dtos import RecurrenceInputDTO


@dataclass(frozen=True, kw_only=True)
class CreateTaskInputDTO(DTO):
    """Data Transfer Object for creating a new Task.

    This DTO is used when a new task is being created. It contains
    all the necessary information to initialize a task entity.
    """

    user_id: str
    title: str
    description: str = ""
    priority: str = Priority.MEDIUM

    context_id: Optional[str] = None
    required_energy_level: int = EnergyLevel.BALANCED

    # Due Date infos
    due_date: Optional[datetime] = None
    is_floating: Optional[bool] = True
    timezone: Optional[str] = None

    # Parent task ID for subtasks
    parent_id: Optional[str] = None

    # List of other tasks ID's that this task depend on
    depends_on: set[str] = field(default_factory=set)

    # Recurrence configuration
    recurrence: Optional[RecurrenceInputDTO] = None


@dataclass(frozen=True, kw_only=True)
class UpdateTaskInputDTO(DTO):
    """Data Transfer Object for updating an existing Task.

    This DTO is used when updating an existing task. It allows
    partial updates, meaning only the provided fields will be changed.
    """

    task_id_prefix: str
    user_id: str

    title: Optional[str] = None
    description: Optional[str] = None
    priority: Optional[str] = None

    context_id: Optional[str] = None
    energy_level: Optional[int] = None

    due_date: Optional[datetime] = None
    is_floating: bool = True
    timezone: Optional[str] = None

    recurrence: Optional[RecurrenceInputDTO] = None


@dataclass(frozen=True, kw_only=True)
class TaskOutputDTO(DTO):
    """Data Transfer Object for returning Task information.

    This DTO is used when returning task details to the client
    or presenter layer. It contains all relevant information
    about a task, including metadata and recurrence display.
    """

    id: str
    title: str
    description: Optional[str] = None
    status: str
    priority: str

    context_name: Optional[str] = None
    context_icon: Optional[str] = None
    required_energy_level: Optional[int] = None
    is_blocked: bool = False

    created_at: datetime
    updated_at: datetime

    parent_id: Optional[str] = None
    due_date: Optional[datetime] = None
    is_overdue: bool = False

    recurrence_display: Optional[str] = None

    next_occurrences: List[datetime] = field(default_factory=list)

    is_in_focus: bool = False


@dataclass(frozen=True, kw_only=True)
class CreateTaskOutputDTO(TaskOutputDTO):
    """Output DTO for task creation.

    Represents the result of creating a new task.
    Inherits all fields from TaskOutputDTO.
    """
    pass


@dataclass(frozen=True)
class TaskByUserRequest(DTO):
    """Request DTO for fetching a task by user.

    Attributes:
        task_id_prefix (str): Prefix of the task ID used for lookup.
        user_id (str): Identifier of the user associated with the task.
        completed_at (Optional[datetime]): Completion timestamp, if available.
    """
    task_id_prefix: str
    user_id: str
    completed_at: Optional[datetime] = None


@dataclass(frozen=True, kw_only=True)
class CompleteTaskOutputDTO(DTO):
    """Composite DTO for the result of completing a task.

    This DTO encapsulates both the completed task and, if applicable,
    the next occurrence generated by recurrence rules.
    """

    completed_task: TaskOutputDTO
    next_occurrence: Optional[TaskOutputDTO] = None


@dataclass(frozen=True, kw_only=True)
class GetTaskRequest(DTO):
    """Input data for retrieving a specific task."""
    task_id_prefix: str
    user_id: str
    n_occurrences: int = 5


@dataclass(frozen=True, kw_only=True)
class ListTasksRequest(DTO):
    """Input data for listing tasks with complex filtering."""

    user_id: str

    status: Optional[str] = None
    priority: Optional[str] = None
    parent_id: Optional[str] = None
    context_id: Optional[str] = None  # Filtro por contexto manual
    max_energy: Optional[int] = None  # Filtro: "mostre o que posso fazer cansado"
    include_blocked: bool = True  # Se False, esconde tarefas com depends_on pendente

    tags: List[str] = field(default_factory=list)
    only_roots: bool = False


@dataclass(frozen=True)
class TaskListOutputDTO(DTO):
    """Output DTO representing a list of tasks.

    Attributes:
        tasks (List[TaskOutputDTO]): Collection of task output DTOs.
    """
    tasks: List[TaskOutputDTO]
