from dataclasses import dataclass, field
from datetime import datetime
from typing import List, Optional

from a_core import DTO
from b_domain.value_objects.enums import EnergyLevel, Priority
from c_application.dtos.recurrence_dtos import RecurrenceInputDTO


@dataclass(frozen=True, kw_only=True)
class CreateTaskInputDTO(DTO):
    """Data Transfer Object for creating a new Task.

    This DTO is used when a new task is being created. It contains
    all the necessary information to initialize a task entity.
    """

    # Core identifiers
    user_id: str
    title: str
    description: str = ""

    # Priority and energy requirements
    priority: int = Priority.MEDIUM.value
    required_energy_level: int = EnergyLevel.BALANCED.value

    # Contextual grouping (e.g., project, workspace)
    context_id: Optional[str] = None

    # Due date information
    due_date: Optional[datetime] = None
    is_floating: Optional[bool] = True
    timezone: Optional[str] = None

    # Hierarchy and dependencies
    parent_id: Optional[str] = None
    depends_on: set[str] = field(default_factory=set)

    # Recurrence configuration
    recurrence: Optional[RecurrenceInputDTO] = None


@dataclass(frozen=True, kw_only=True)
class UpdateTaskInputDTO(DTO):
    """Data Transfer Object for updating an existing Task.

    This DTO is used when updating an existing task. It allows
    partial updates, meaning only the provided fields will be changed.
    """

    # Core identifiers
    task_id_prefix: str
    user_id: str

    # Editable fields (optional for partial updates)
    title: Optional[str] = None
    description: Optional[str] = None
    priority: Optional[str] = None

    # Contextual grouping and energy requirements
    context_id: Optional[str] = None
    energy_level: Optional[int] = None

    # Due date information
    due_date: Optional[datetime] = None
    is_floating: bool = True
    timezone: Optional[str] = None

    # Recurrence configuration
    recurrence: Optional[RecurrenceInputDTO] = None


@dataclass(frozen=True, kw_only=True)
class TaskOutputDTO(DTO):
    """Data Transfer Object for returning Task information.

    This DTO is used when returning task details to the client
    or presenter layer. It contains all relevant information
    about a task, including metadata, deadlines, and recurrence display.
    """

    # Core identifiers and metadata
    id: str
    title: str
    description: Optional[str] = None
    status: str
    priority: str

    # Contextual information (project, workspace, etc.)
    context_name: Optional[str] = None
    context_icon: Optional[str] = None
    required_energy_level: Optional[int] = None
    is_blocked: bool = False

    # Audit timestamps
    created_at: datetime
    updated_at: datetime

    # Hierarchy and deadlines
    parent_id: Optional[str] = None
    due_date: Optional[datetime] = None
    is_overdue: bool = False

    # Recurrence and scheduling
    recurrence_display: Optional[str] = None
    next_occurrences: List[datetime] = field(default_factory=list)

    # Focus state (e.g., currently active or highlighted)
    is_in_focus: bool = False


@dataclass(frozen=True, kw_only=True)
class CreateTaskOutputDTO(TaskOutputDTO):
    """Output DTO for task creation.

    Represents the result of creating a new task.
    Inherits all fields from TaskOutputDTO.
    """


@dataclass(frozen=True)
class TaskByUserRequest(DTO):
    """Request DTO for fetching a task by user.

    This DTO is used when requesting a specific task associated
    with a given user. It provides the identifiers needed for lookup
    and optionally includes completion metadata.
    """

    # Identifiers
    task_id_prefix: str
    user_id: str

    # Completion metadata
    completed_at: Optional[datetime] = None


@dataclass(frozen=True, kw_only=True)
class CompleteTaskOutputDTO(DTO):
    """Composite DTO for the result of completing a task.

    This DTO encapsulates both the completed task and, if applicable,
    the next occurrence generated by recurrence rules.
    """

    # The task that has just been completed
    completed_task: TaskOutputDTO

    # The next occurrence of the task, if recurrence rules apply
    next_occurrence: Optional[TaskOutputDTO] = None


@dataclass(frozen=True, kw_only=True)
class GetTaskRequest(DTO):
    """Request DTO for retrieving a specific task.

    This DTO is used when fetching details of a task associated
    with a given user. It supports retrieving multiple upcoming
    occurrences if the task is recurrent.
    """

    # Identifiers
    task_id_prefix: str
    user_id: str

    # Number of next occurrences to fetch, if applicable (default: 5)
    n_occurrences: int = 5


@dataclass(frozen=True, kw_only=True)
class ListTasksRequest(DTO):
    """Request DTO for listing tasks with comprehensive filtering and pagination.

    This DTO mirrors the TaskFilter but uses primitive types to decouple
    the Application layer from Domain Value Objects. It allows flexible
    filtering, sorting, and pagination when retrieving tasks.
    """

    # Identifiers
    ids: Optional[List[str]] = None
    user_id: str
    parent_id: Optional[str] = None

    # Status & Priority
    status: Optional[str] = None
    priority: Optional[str] = None

    # GTD & Organization
    context_id: Optional[str] = None
    max_energy: Optional[int] = None
    complexity: Optional[str] = None
    tags: List[str] = field(default_factory=list)

    # Behavior Flags
    include_blocked: bool = True   # Maps to is_blocked in TaskFilter
    is_recurring: Optional[bool] = None
    only_roots: bool = False

    # Temporal Filters (Task Specific)
    due_before: Optional[datetime] = None
    due_after: Optional[datetime] = None

    # Pagination (from BaseFilter)
    limit: int = 100
    offset: int = 0

    # Auditing Filters (from BaseFilter)
    created_after: Optional[datetime] = None
    created_before: Optional[datetime] = None
    updated_after: Optional[datetime] = None
    updated_before: Optional[datetime] = None


@dataclass(frozen=True)
class TaskListOutputDTO(DTO):
    """Output DTO representing a list of tasks.

    This DTO is used when returning a collection of tasks to the client
    or presenter layer. It encapsulates multiple task details in a single
    response, typically after applying filters or pagination.
    """

    # Collection of task output DTOs
    tasks: List[TaskOutputDTO]
